name: flutter_flavor_example
description: Demonstrates how to use the flutter_flavor plugin.

dependencies:
  flutter:
    sdk: flutter
  flutter_flavor:
    path: ../

dev_dependencies:
  e2e: "^0.2.0"
  flutter_driver:
    sdk: flutter
  pedantic: ^1.8.0

flutter:
  uses-material-design: true
